### ISSUE TITLE
Add Snyk vulnerability monitoring

### ISSUE THREAD

**Issue by cadecairos** [mozilla/network-pulse#717]
Let's add a Snyk vulnerability check on our dependencies in this project. See https://github.com/mozilla/network/pull/733 for reference.

also, [Snyk docs](https://snyk.io/docs)

**Comment by kunal12422** [comment]
Hey, @cadecairos I would like to work on this issue.

**Comment by cadecairos** [comment]
Hi @kunal12422, I've assigned the issue to you. We'll need to coordinate to get the SNYK_TOKEN set up properly. I can handle the encryption of it for Travis and Appveyor, and pass to you here.

**Comment by kunal12422** [comment]
@cadecairos perfect. :smile:

**Comment by kunal12422** [comment]
@cadecairos great. :+1:

**Comment by kunal12422** [comment]
Hi, @cadecairos, can you please provide SNYK_TOKEN for Travis and Appveyor.

**Comment by cadecairos** [comment]
@kunal12422 I'll get those for you today.

**Comment by cadecairos** [comment]
@kunal12422 Here are the encrypted values:

#### `.travis.yml`

```yaml
env:
  global:
    secure: g9BqtXjvVNNvF9lddICMaGnVGkG4ZwJUcC7KcShS8J7/UYx0WSmWvpelMFWzY71Tt7NlohWJGccXT4Qcs1uK76VgBSbjjGuX1EMSEPdYjfgWhpzBZo3NBslMQaEbet26f0UoPvIN18E0OAw3raer41ng4S7ZMmuHhIdw0i1Z7QuGwlDDEO+sLIjiSyYd0fqCDRYe3G4TEA6Ju1r8aw5JvkLozHItZNOF1s2vOA8wtJd0Y5PeBYEV1HbBA2TSZJJyHbNUuan1nqcb/hNyLYCcl+qve4H08g4zEGQR9MgD1AXp68zRzQ1QAhMA1VkUFv0yN6N+0Gl+E871euJcaX/wlYZMQb1DhY/0cvgVR1+orbSYVuL91INJAguQIGByy3EexMLNFpjnNpCPR4RalioPrBUYZrtijgWvH1WE3nfk2UJBlUwDXcLq7IBc91jba3g+vdwPJwATglRszNAraCeSrgx5y5ccuf/wejc/DD2G9i8dxqd/qVr+gjagzrwxQxq5GpKLqDtZLV3kASBcjdepEqbZ511Cm60PdfSNK6xwfiM31iDVb7l7+xywQAJSgGQMjAslsLGa1Mhw6PBsercXOp3uZZyc5/JqHyc0iIpGFBlDj7BZMwDbailylAHl9zcqyrJsHbiJ8QR6XlOF+/h3bWsfdLHhEIO3/z0M4EHusYQ=
```

#### `appveyor.yml`

```yaml
environment:
  SNYK_TOKEN:
    secure: 2HH1+J++C/e7GSlklkVgJJhL+2EMiqq73aDu/PyU7O5EECduDRxm9qFfrZFf9HmH
```
